import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <div className={styles.centerarrow}>
        <h3>&rarr;</h3>
      </div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className={styles.title}>FitGoals</h1>
        <p className={styles.description}>
          Enter in your information down below to get your workout
        </p>
        <div className={styles.grid}>
          <form>
            <div className={styles.card}>
              <h3>Age</h3>
              <input required type="number" />
            </div>
            <div className={styles.card}>
              <h3>Weight</h3>
              <input required type="number" />
            </div>
            <div className={styles.card}>
              <h3>Height </h3>
              <input required type="number" />
            </div>
            <div className={styles.card}>
              <h3>Neck </h3>
              <input required type="number" />
            </div>
            <div className={styles.card}>
              <h3>Chest </h3>
              <input required type="number" />
            </div>
            <div className={styles.card}>
              <h3>Abdomen </h3>
              <input required type="number" />
            </div>
            <div className={styles.card}>
              <h3>Hip </h3>
              <input required type="number" />
            </div>
            <div className={styles.card}>
              <h3>Thigh </h3>
              <input required type="number" />
            </div>
            <div className={styles.card}>
              <h3>Knee </h3>
              <input required type="number" />
            </div>
            <div className={styles.card}>
              <h3>Ankle </h3>
              <input required type="number" />
            </div>
            <div className={styles.card}>
              <h3>Biceps </h3>
              <input required type="number" />
            </div>
            <div className={styles.card}>
              <h3>Forearm </h3>
              <input required type="number" />
            </div>
            <div className={styles.card}>
              <h3>Wrist </h3>
              <input required type="number" />
            </div>
            <div className={styles.card}>
              <input type="submit" value="Submit" />
            </div>
          </form>
        </div>
      </main>
    </div>
  );
}
