import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          FitGoals 
        </h1>

        <p className={styles.description}>
          Enter in your information down below to get your workout 
          
        </p>
            
        <div className={styles.grid}>
            
              <form>
                <div className={styles.card}>
                <h3>Bodyfat</h3>
                <form >
                <input required type="number" />
                </form>
                </div>
              
                <div className={styles.card}>
                <h3>Age
                </h3>
                <form >
                <input required type="number" />
                </form>
                </div>
            
                <div className={styles.card}>
                <h3>Weight</h3>
                <form >
                <input required type="number" />
                </form>
                </div>
              

                <div className={styles.card}>
                <h3>Height </h3>
                <form >
                <input required type="number" />
                </form>
                </div>

                <div className={styles.card}>
                <h3>Neck </h3>
                <form >
                <input required type="number" />
                </form>
                </div>

                <div className={styles.card}>
                <h3>Chest </h3>
                <form >
                <input required type="number" />
                </form>
                </div>

                <div className={styles.card}>
                <h3>Abdomen </h3>
                <form >
                <input required type="number" />
                </form>
                </div>
              
                <div className={styles.card}>
                <h3>Hip </h3>
                <form >
                <input required type="number" />
                </form>
                </div>
                
                <div className={styles.card}>
                <h3>Thigh </h3>
                <form >
                <input required type="number" />
                </form>
                </div>

                <div className={styles.card}>
                <h3>Knee </h3>
                <form >
                <input required type="number" />
                </form>
                </div>

                <div className={styles.card}>
                <h3>Ankle </h3>
                <form >
                <input required type="number" />
                </form>
                </div>

                <div className={styles.card}>
                <h3>Biceps </h3>
                <form >
                <input required type="number" />
                </form>
                </div>

                <div className={styles.card}>
                <h3>Forearm </h3>
                <form >
                <input required type="number" />
                </form>
                </div>

                <div className={styles.card}>
                <h3>Wrist </h3>
                <form >
                <input required type="number" />
                </form>
                </div>

                <div className={styles.card}>
                <input type="submit" value="Submit" />
                </div>
              </form>
        </div>

        <div className={styles.centerarrow}>
          <center>
          <h3>&rarr;</h3>
          </center>
        </div>
      </main>

      
    </div>
  );
}
